services:
  backend:
    container_name: backend_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DB_HOST: dpg-ctvhkdd2ng1s73d54gcg-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_DATABASE: taller3backend
      DB_USER: root
      DB_PASSWORD: 6MmHbSFZUTuNgFmZSbQS9DRI0qQRn8yx
      TOKEN_SECRET: mysecretkey
    networks:
      - taller3-network
networks:
  taller3-network:
    driver: bridge